#!/bin/bash

# general config
. /etc/rc.conf
. /etc/rc.d/functions

_bin=$(type -pf krb5kdc)
_pid=$(pidof -o %PPID krb5kdc)

case "$1" in
    start)
		if [ -z "$PID" ];then
			exec_cmd "Starting Kerberos Authentication" "$_bin"
        fi
        ;;
    stop)
	    if [ -n "$PID" ];then
			exec_cmd "Stopping Kerberos Authentication" kill "$_pid"
		fi
        ;;
    restart)
        $0 stop
	sleep 1
        $0 start
        ;;
    *)
        echo "usage: $0 {start|stop|restart}"
	;;
esac
